version: '1'
services:
    session1:
        build: '.'
        environment: 
            - APP_ID=session1
            ports: 
                - "9000:9000"

    nginx:
        image: nginx:latest
        ports: 
            - 8080:8080
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - session1 